name: Service A CI/CD

on:
  push:
    paths:
      - 'apps/service-a/**'
  pull_request:
    paths:
      - 'apps/service-a/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/service-a
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Lint and test
        run: |
          go fmt ./...
          go vet ./...
          go test ./...

      - name: Trivy scan (FS)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          scan-ref: apps/service-a

      - name: Build Docker image
        run: |
          docker build -t fvnilo/service-a:${{ github.sha }} .

      - name: Push Docker image
        run: |
          echo "docker push fvnilo/service-a:${{ github.sha }}"

      - name: Deploy to Dev
        if: github.ref != 'refs/heads/main'
        run: |
          echo "Deploying service-a to Dev with image fvnilo/service-a:${{ github.sha }}"
