name: Service B CI/CD

on:
  push:
    paths:
      - '.github/workflows/service-b.yaml'
      - 'apps/service-b/**'
      - 'libs/reverse_go/**'
  pull_request:
    paths:
      - '.github/workflows/service-b.yaml'
      - 'apps/service-b/**'
      - 'libs/reverse_go/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Lint and test
        working-directory: apps/service-b
        run: |
          go mod tidy
          go fmt ./...
          go vet ./...
          go test ./...

      - name: Trivy scan (FS)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          scan-ref: apps/service-b

      - name: Build Docker image
        run: |
          docker build -t fvnilo/service-b:${{ github.sha }} -f apps/service-b/Dockerfile .

      - name: Push Docker image
        run: |
          echo "docker push fvnilo/service-b:${{ github.sha }}"

      - name: Deploy to Dev
        if: github.ref != 'refs/heads/main'
        run: |
          echo "Deploying service-b to Dev with image fvnilo/service-b:${{ github.sha }}"
